apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-app-web-deployment
  labels:
    app: bg-app-web-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bg-app-web-service
  template:
    metadata:
      labels:
        app: bg-app-web-service
    spec:
      containers:
      - name: bg-app-web
        image: borisk0/bg-app-web
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: nodeport-for-bg-app
spec:
 type: NodePort
 selector:
   app: bg-app-web-service
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 30001
