version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: dockerfile.web
        ports:
            - 8080:80
        volumes:
            - "/home/bobi/git/borkos/web:/var/www/html:ro"
        networks:
            - app-net
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: dockerfile.db
        networks:
            - app-net
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
  app-net:

